spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/lyncasDB?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root123*
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: cHJlc3Mgc3RhcnQgw6kgbyBtZWxob3I=
springdoc:
  swagger-ui:
    path: /swagger-ui.html










